name: Pull Request
on:
  pull_request:
    branches:
      - master

# flow:
# +------------------------------------+          +-------------------+
# |Static-Checks (Licenses, Lint, Jest)|          |Build-Documentation|
# +----------+-------------------------+          +---------+---------+
#            |                                              |
#            |                   +-----------+----------------------------------------+
#            |                   |           |              |                         |
#            |             +-----v----+ +----v-----+ +------v----------------+ +------v----------+
#            |             |A11Y-Tests| |Applitools| |Robot (chrome, firefox)| |Github-Deployment|
#            |             +--------+-+ +--+-------+ +------+----------------+ +------+----------+
#            |                      |      |                |                         |
#            |                      |      |                |                         |
#            |                      |      |                |                         |
#            |                    +-v------v-+              |                         |
#            +------------------->|Notify-End|<-------------+-------------------------+
#                                 +----------+

# env:
#   RESOLVE_REGISTRY: https://repo.orl.eng.hitachivantara.com/artifactory/api/npm/npm/
#   DOCUMENTATION_PUBLISH_REPO: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
#   DOCUMENTATION_PUBLISH_BRANCH: master
#   DOCUMENTATION_PUBLISH_FOLDER: uikit/pr-${{ github.event.number }}
#   DOCUMENTATION_PUBLISH_MESSAGE: "docs: storybook for PR ${{ github.repository }}#${{ github.event.number }}"
#   DOCUMENTATION_URL: https://${{ github.repository_owner }}.github.io/uikit/pr-${{ github.event.number }}/
#   PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
#   RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  Static-Checks:
    name: Licenses, Lint, Jest
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: License Check
        run: npm run license-check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
